<?php

/**
 * @file
 * XML Forms base module.
 */

/**
 * Get the schema if it exists.
 *
 * @param string $filename
 *   XSD to grab the schema from.
 */
function xml_forms_get_schema($filename) {
  $path = drupal_get_path('module', 'xml_forms') . '/schema';
  $full_filename = "$path/$filename";
  if (file_exists($full_filename)) {
    drupal_goto($full_filename);
  }
  else {
    drupal_not_found();
  }
}
